<?php

namespace Proxies\__CG__\GSB\VisiteurBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class fiche_frais extends \GSB\VisiteurBundle\Entity\fiche_frais implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\fiche_frais' . "\0" . 'id', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\fiche_frais' . "\0" . 'etat', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\fiche_frais' . "\0" . 'mois', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\fiche_frais' . "\0" . 'idVisiteur', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\fiche_frais' . "\0" . 'nbJustificatifs', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\fiche_frais' . "\0" . 'montantValide', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\fiche_frais' . "\0" . 'dateNotif'];
        }

        return ['__isInitialized__', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\fiche_frais' . "\0" . 'id', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\fiche_frais' . "\0" . 'etat', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\fiche_frais' . "\0" . 'mois', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\fiche_frais' . "\0" . 'idVisiteur', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\fiche_frais' . "\0" . 'nbJustificatifs', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\fiche_frais' . "\0" . 'montantValide', '' . "\0" . 'GSB\\VisiteurBundle\\Entity\\fiche_frais' . "\0" . 'dateNotif'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (fiche_frais $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMois($mois)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMois', [$mois]);

        return parent::setMois($mois);
    }

    /**
     * {@inheritDoc}
     */
    public function getMois()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMois', []);

        return parent::getMois();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdVisiteur($idVisiteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdVisiteur', [$idVisiteur]);

        return parent::setIdVisiteur($idVisiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdVisiteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdVisiteur', []);

        return parent::getIdVisiteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbJustificatifs($nbJustificatifs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbJustificatifs', [$nbJustificatifs]);

        return parent::setNbJustificatifs($nbJustificatifs);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbJustificatifs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbJustificatifs', []);

        return parent::getNbJustificatifs();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantValide($montantValide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantValide', [$montantValide]);

        return parent::setMontantValide($montantValide);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantValide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantValide', []);

        return parent::getMontantValide();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNotif($dateNotif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNotif', [$dateNotif]);

        return parent::setDateNotif($dateNotif);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNotif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNotif', []);

        return parent::getDateNotif();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(\GSB\VisiteurBundle\Entity\etat $etat = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function getFF()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFF', []);

        return parent::getFF();
    }

    /**
     * {@inheritDoc}
     */
    public function getLeVisiteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeVisiteur', []);

        return parent::getLeVisiteur();
    }

    /**
     * {@inheritDoc}
     */
    public function getLeEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeEtat', []);

        return parent::getLeEtat();
    }

}
