<?php

namespace GSB\VisiteurBundle\Repository;

use Symfony\Component\HttpFoundation\Session\Session;

/**
 * fiche_fraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fiche_fraisRepository extends \Doctrine\ORM\EntityRepository
{

    public function allFF()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('ff')
            ->from('GSBVisiteurBundle:fiche_frais', 'ff')
            ->orderBy('ff.dateNotif');
        $query = $qb->getQuery();
        $result = $query->getResult();
        return $result;
    }

    public function getFF($id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('ff')
            ->from('GSBVisiteurBundle:fiche_frais', 'ff')
            ->where('ff.idVisiteur = :id')
            ->orderBy('ff.dateNotif')
            ->setParameter('id', $id);
        $query = $qb->getQuery();
        $result = $query->getResult();
        return $result;
    }

    public function getFFOne($id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('ff')
            ->from('GSBVisiteurBundle:fiche_frais', 'ff')
            ->where('ff.idVisiteur = :id')
            ->orderBy('ff.dateNotif')
            ->setParameter('id', $id);
        $query = $qb->getQuery();
        $result = $query->getOneOrNullResult();
        return $result;
    }

    public function getUnFF($id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('ff')
            ->from('GSBVisiteurBundle:fiche_frais', 'ff')
            ->where('ff.id = :id')
            ->setParameter('id', $id);
        $query = $qb->getQuery();
        $result = $query->getSingleResult();
        return $result;
    }

    public function getByMois($mois, $id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('ff')
            ->from('GSBVisiteurBundle:fiche_frais', 'ff')
            ->where('ff.idVisiteur = :id')
            ->andWhere('ff.mois = :mois')
            ->setParameter('id', $id)
            ->setParameter('mois', $mois);
        $query = $qb->getQuery();
        $result = $query->getOneOrNullResult();
        return $result;
    }

}
