<?php

namespace GSB\VisiteurBundle\Repository;

/**
 * ligne_frais_hors_forfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ligne_frais_hors_forfaitRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLFHF($id)
    {
        $ss_qb = $this->_em->createQueryBuilder();
        $ss_qb->select('ff.id')
            ->from('GSBVisiteurBundle:fiche_frais', 'ff')
            ->where('ff.idVisiteur = :id');

        $qb = $this->_em->createQueryBuilder();
        $qb->select('lfhf')
            ->from('GSBVisiteurBundle:ligne_frais_hors_forfait', 'lfhf')
            ->where($qb->expr()->in('lfhf.ficheFrais', $ss_qb->getDQL()))
            ->orderBy('lfhf.date')
            ->setParameter('id', $id);
        $query = $qb->getQuery();
        $result = $query->getResult();
        return $result;
    }

    public function getLFHFSynt($mois, $visiteur)
    {
        $ss_qb = $this->_em->createQueryBuilder();
        $ss_qb->select('ff.id')
            ->from('GSBVisiteurBundle:fiche_frais', 'ff')
            ->where('ff.idVisiteur = :visiteur')
            ->andWhere('ff.mois = :mois');

        $qb = $this->_em->createQueryBuilder();
        $qb->select('lfhf')
            ->from('GSBVisiteurBundle:ligne_frais_hors_forfait', 'lfhf')
            ->where($qb->expr()->in('lfhf.ficheFrais', $ss_qb->getDQL()))
            ->setParameter('visiteur', $visiteur)
            ->setParameter('mois', $mois);
        $query = $qb->getQuery();
        $result = $query->getResult();
        return $result;
    }

    public function getUnLFHF($id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('lfhf')
            ->from('GSBVisiteurBundle:ligne_frais_hors_forfait', 'lfhf')
            ->where('lfhf.id = :id')
            ->setParameter('id', $id);
        $query = $qb->getQuery();
        $result = $query->getOneOrNullResult();
        return $result;
    }

}
