<?php

namespace GSB\VisiteurBundle\Repository;

/**
 * visiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class visiteurRepository extends \Doctrine\ORM\EntityRepository
{

    public function getVisiteur($id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('v')
            ->from('GSBVisiteurBundle:visiteur', 'v')
            ->where('v.user = :id')
            ->setParameter('id', $id);
        $query = $qb->getQuery();
        $result = $query->getOneOrNullResult();
        return $result;
    }

    public function getLeVisiteur($id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('v')
            ->from('GSBVisiteurBundle:visiteur', 'v')
            ->where('v.id = :id')
            ->setParameter('id', $id);
        $query = $qb->getQuery();
        $result = $query->getOneOrNullResult();
        return $result;
    }

}